# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: products-api
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
          Resource:
            - { "Fn::GetAtt": ["ProductsTable", "Arn"] }
            - { "Fn::GetAtt": ["CategoriesTable", "Arn"] }


functions:
  createProduct:
    handler: src/product.createProduct
    events:
      - httpApi:
          path: /product
          method: post
  addImageToProduct:
    handler: src/product.addImageToProduct
    events:
      - httpApi:
          path: /product/addImage/{id}
          method: put
  getProduct:
    handler: src/product.getProduct
    events:
      - httpApi:
          path: /product/{id}
          method: get
  updateProduct:
    handler: src/product.updateProduct
    events:
      - httpApi:
          path: /product/{id}
          method: put
  deleteProduct:
    handler: src/product.deleteProduct
    events:
      - httpApi:
          path: /product/{id}
          method: delete
  listProduct:
    handler: src/product.listProduct
    events:
      - httpApi:
          path: /products
          method: get
  createCategory:
    handler: src/category.createCategory
    events:
      - httpApi:
          path: /category
          method: post
  addImageToCategory:
    handler: src/category.addImageToCategory
    events:
      - httpApi:
          path: /category/addImage/{id}
          method: put
  getCategory:
    handler: src/category.getCategory
    events:
      - httpApi:
          path: /category/{id}
          method: get
  updateCategory:
    handler: src/category.updateCategory
    events:
      - httpApi:
          path: /category/{id}
          method: put
  deleteCategory:
    handler: src/category.deleteCategory
    events:
      - httpApi:
          path: /category/{id}
          method: delete
  listCategory:
    handler: src/category.listCategory
    events:
      - httpApi:
          path: /categories
          method: get


plugins:
  - serverless-plugin-typescript

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ProductsTable
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: productID
            AttributeType: S
        KeySchema:
          - AttributeName: productID
            KeyType: HASH
    CategoriesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CategoriesTable
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: categoryID
            AttributeType: S
        KeySchema:
          - AttributeName: categoryID
            KeyType: HASH
